project_name: kubectl-db-restore
release:
  github:
    owner: wiremind
    name: kubectl-db-restore
builds:
  - id: kubectl-db-restore
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/wiremind/kubectl-db-restore/pkg/version.version=
archives:
  - id: kubectl-db-restore
    builds:
    - kubectl-db-restore
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
