apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-restore
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/wiremind/kubectl-restore/releases/download/v0.1.0/kubectl-restore_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-restore"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-restore"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/wiremind/kubectl-restore/releases/download/v0.1.0/kubectl-restore_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-restore"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-restore"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/wiremind/kubectl-restore/releases/download/v0.1.0/kubectl-restore_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-restore.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-restore.exe"
  shortDescription: A new plugin
  homepage: https://github.com/wiremind/kubectl-restore
  caveats: |
    Usage:
      $ kubectl kubectl-restore

    For additional options:
      $ kubectl kubectl-restore --help
      or https://github.com/wiremind/kubectl-restore/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
