name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  golang:
    name: Golang
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
